import 'reflect-metadata'
import '@a11d/constructor'
import '@a11d/key-path'
export * from './createMetadataDecorator.js'
export * from './type.js'
import './type.js'
export * from './label.js'
import './label.js'
export * from './description.js'
import './description.js'